import { THEMES } from './theme';
import {
  ALL_DEFAULT_SETTINGS,
  COUNTDOWN_DEFAULT_SETTINGS,
  DOTS_DEFAULT_SETTINGS,
  PIE_DEFAULT_SETTINGS,
  PROGRESS_DEFAULT_SETTINGS,
} from './viewSettings';

const RAW_SAMPLE_ITEMS = [
  {
      id: 'all-mint-topfield',
      label: 'All / Mint Topfield',
      frame: 'square',
      viewId: 'all',
      theme: THEMES.DARK,
      viewState: {
        ...ALL_DEFAULT_SETTINGS,
        dotsMode: 'custom',
        dotsCount: 365,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#34d399',
        alternate: '#000000',
      },
    },
  {
      id: 'countdown-clean',
      label: 'Countdown / Clean',
      viewId: 'countdown',
      theme: THEMES.DARK,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'all',
        labels: true,
        frame: false,
        fontSize: 0.9,
        spaceTop: 10,
        spaceRight: 8,
        spaceBottom: 8,
        spaceLeft: 8,
        primary: '#ffffff',
        alternate: '#000000',
      },
    },
  {
      id: 'pie-circle-outline',
      label: 'Pie / Circle Outline',
      frame: 'square',
      viewId: 'pie',
      theme: THEMES.DARK,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'circle',
        style: 'outline',
        fullScreen: true,
        decimals: 1,
        spaceTop: 3,
        spaceRight: 3,
        spaceBottom: 3,
        spaceLeft: 3,
        primary: '#22d3ee',
        alternate: '#0f172a',
      },
    },
  {
      id: 'dots-circles',
      label: 'Dots / Circles',
      viewId: 'dots',
      theme: THEMES.DARK,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'circle',
        gapX: 0.45,
        gapY: 0.45,
        inactiveOpacity: 4,
        spaceTop: 3,
        spaceRight: 3,
        spaceBottom: 3,
        spaceLeft: 3,
        primary: '#ffffff',
        alternate: '#000000',
      },
    },
  {
      id: 'progress-line',
      label: 'Progress / Line',
      frame: 'landscape',
      viewId: 'progress',
      theme: THEMES.LIGHT,
      viewState: {
        ...PROGRESS_DEFAULT_SETTINGS,
        mode: 'line',
        fullScreen: true,
        decimals: 6,
        fontSize: 0.85,
        lineWidth: 18,
        spaceTop: 10,
        spaceRight: 6,
        spaceBottom: 10,
        spaceLeft: 6,
        primary: '#000000',
        alternate: '#ffffff',
      },
    },
  {
      id: 'all-minimal',
      label: 'All / Minimal',
      frame: 'square',
      viewId: 'all',
      theme: THEMES.LIGHT,
      viewState: {
        ...ALL_DEFAULT_SETTINGS,
        dotsMode: 'custom',
        dotsCount: 120,
        showDays: true,
        showPercentBox: true,
        showPerimeter: false,
        shape: 'square',
        summaryLayout: 'row',
        gapX: 0.4,
        gapY: 0.4,
        spaceTop: 4,
        spaceRight: 4,
        spaceBottom: 4,
        spaceLeft: 4,
        primary: '#2563eb',
        alternate: '#ffffff',
      },
    },
  {
      id: 'countdown-days',
      label: 'Countdown / Days',
      viewId: 'countdown',
      theme: THEMES.LIGHT,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'days',
        labels: true,
        frame: false,
        fontSize: 0.7,
        spaceTop: 12,
        spaceRight: 8,
        spaceBottom: 8,
        spaceLeft: 8,
        primary: '#0f172a',
        alternate: '#f8fafc',
      },
    },
  {
      id: 'pie-rect',
      label: 'Pie / Rectangle',
      viewId: 'pie',
      theme: THEMES.LIGHT,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'rectangle',
        style: 'filled',
        fullScreen: true,
        decimals: 1,
        spaceTop: 4,
        spaceRight: 4,
        spaceBottom: 4,
        spaceLeft: 4,
        primary: '#ea580c',
        alternate: '#ffffff',
      },
    },
  {
      id: 'dots-squares',
      label: 'Dots / Squares',
      frame: 'square',
      viewId: 'dots',
      theme: THEMES.LIGHT,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'square',
        gapX: 0.35,
        gapY: 0.35,
        inactiveOpacity: 5,
        spaceTop: 4,
        spaceRight: 4,
        spaceBottom: 4,
        spaceLeft: 4,
        primary: '#b91c1c',
        alternate: '#fffaf0',
      },
    },
  {
      id: 'progress-field',
      label: 'Progress / Field',
      viewId: 'progress',
      theme: THEMES.DARK,
      viewState: {
        ...PROGRESS_DEFAULT_SETTINGS,
        mode: 'field',
        fullScreen: true,
        decimals: 1,
        fontSize: 1,
        spaceTop: 6,
        spaceRight: 6,
        spaceBottom: 6,
        spaceLeft: 6,
        primary: '#7c3aed',
        alternate: '#f5f5dc',
      },
    },
  {
      id: 'all-composed',
      label: 'All / Composed',
      frame: 'square',
      viewId: 'all',
      theme: THEMES.DARK,
      viewState: {
        ...ALL_DEFAULT_SETTINGS,
        dotsMode: 'custom',
        dotsCount: 12,
        showDays: true,
        showPercentBox: true,
        showPerimeter: true,
        shape: 'circle',
        percentBoxSize: 'medium',
        perimeterThickness: 6,
        gapX: 0.45,
        gapY: 0.45,
        spaceTop: 3,
        spaceRight: 3,
        spaceBottom: 3,
        spaceLeft: 3,
        primary: '#ffffff',
        alternate: '#000000',
      },
    },
  {
      id: 'countdown-seconds',
      label: 'Countdown / Seconds',
      frame: 'square',
      viewId: 'countdown',
      theme: THEMES.DARK,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'seconds',
        labels: false,
        frame: false,
        fontSize: 0.35,
        spaceTop: 14,
        spaceRight: 8,
        spaceBottom: 8,
        spaceLeft: 8,
        primary: '#22d3ee',
        alternate: '#0f172a',
      },
    },
  {
      id: 'pie-cobalt-square',
      label: 'Pie / Cobalt Cream',
      frame: 'square',
      viewId: 'pie',
      theme: THEMES.LIGHT,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'circle',
        style: 'filled',
        fullScreen: true,
        decimals: 1,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#1d4ed8',
        alternate: '#fff7ed',
      },
    },
  {
      id: 'dots-coral-square',
      label: 'Dots / Coral Grid',
      frame: 'square',
      viewId: 'dots',
      theme: THEMES.DARK,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'square',
        gapX: 0.5,
        gapY: 0.5,
        inactiveOpacity: 8,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#fb7185',
        alternate: '#111827',
      },
    },
  {
      id: 'progress-cyan-landscape',
      label: 'Progress / Cyan Field',
      frame: 'landscape',
      viewId: 'progress',
      theme: THEMES.DARK,
      viewState: {
        ...PROGRESS_DEFAULT_SETTINGS,
        mode: 'field',
        fullScreen: true,
        decimals: 0,
        fontSize: 0.95,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#22d3ee',
        alternate: '#0f172a',
      },
    },
  {
      id: 'all-violet-square',
      label: 'All / Violet Sand',
      frame: 'square',
      viewId: 'all',
      theme: THEMES.LIGHT,
      viewState: {
        ...ALL_DEFAULT_SETTINGS,
        dotsMode: 'custom',
        dotsCount: 144,
        showDays: true,
        showPercentBox: true,
        showPerimeter: true,
        shape: 'circle',
        percentBoxSize: 'small',
        perimeterThickness: 5,
        gapX: 0.4,
        gapY: 0.4,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#7c3aed',
        alternate: '#f5f5dc',
      },
    },
  {
      id: 'pie-rect-coral-landscape',
      label: 'Pie / Coral Rectangle',
      frame: 'landscape',
      viewId: 'pie',
      theme: THEMES.DARK,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'rectangle',
        style: 'filled',
        fullScreen: true,
        decimals: 1,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#fb7185',
        alternate: '#111827',
      },
    },
  {
      id: 'countdown-crimson-square',
      label: 'Countdown / Crimson',
      frame: 'square',
      viewId: 'countdown',
      theme: THEMES.LIGHT,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'hours',
        labels: true,
        frame: false,
        fontSize: 0.65,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#b91c1c',
        alternate: '#fffaf0',
      },
    },
  {
      id: 'dots-chartreuse-landscape',
      label: 'Dots / Chartreuse Field',
      frame: 'landscape',
      viewId: 'dots',
      theme: THEMES.DARK,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'circle',
        gapX: 0.35,
        gapY: 0.35,
        inactiveOpacity: 6,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#bef264',
        alternate: '#000000',
      },
    },
  {
      id: 'pie-circle-filled',
      label: 'Pie / Circle Filled',
      viewId: 'pie',
      theme: THEMES.LIGHT,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'circle',
        style: 'filled',
        fullScreen: false,
        decimals: 2,
        spaceTop: 8,
        spaceRight: 8,
        spaceBottom: 8,
        spaceLeft: 8,
        primary: '#b91c1c',
        alternate: '#fffaf0',
      },
    },
  {
      id: 'dots-triangles',
      label: 'Dots / Triangles',
      viewId: 'dots',
      theme: THEMES.DARK,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'triangle',
        triangleMode: 'alternating',
        gapX: 0.6,
        gapY: 0.5,
        inactiveOpacity: 7,
        spaceTop: 4,
        spaceRight: 4,
        spaceBottom: 5,
        spaceLeft: 4,
        primary: '#34d399',
        alternate: '#000000',
      },
    },
  {
      id: 'pie-rect-outline',
      label: 'Pie / Rectangle Outline',
      viewId: 'pie',
      theme: THEMES.DARK,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'rectangle',
        style: 'outline',
        fullScreen: true,
        decimals: 0,
        spaceTop: 4,
        spaceRight: 4,
        spaceBottom: 4,
        spaceLeft: 4,
        primary: '#bef264',
        alternate: '#000000',
      },
    },
  {
      id: 'countdown-minutes-amber',
      label: 'Countdown / Minutes Amber',
      frame: 'portrait',
      viewId: 'countdown',
      theme: THEMES.LIGHT,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'minutes',
        labels: false,
        frame: false,
        fontSize: 0.75,
        spaceTop: 8,
        spaceRight: 8,
        spaceBottom: 8,
        spaceLeft: 8,
        primary: '#f59e0b',
        alternate: '#fffbeb',
      },
    },
  {
      id: 'countdown-hours-mint',
      label: 'Countdown / Hours Mint',
      frame: 'square',
      viewId: 'countdown',
      theme: THEMES.DARK,
      viewState: {
        ...COUNTDOWN_DEFAULT_SETTINGS,
        mode: 'hours',
        labels: true,
        frame: false,
        fontSize: 0.72,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#34d399',
        alternate: '#052e16',
      },
    },
  {
      id: 'dots-ivory-circles',
      label: 'Dots / Ivory Circles',
      frame: 'portrait',
      viewId: 'dots',
      theme: THEMES.LIGHT,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'circle',
        gapX: 0.4,
        gapY: 0.4,
        inactiveOpacity: 5,
        spaceTop: 2,
        spaceRight: 2,
        spaceBottom: 2,
        spaceLeft: 2,
        primary: '#111827',
        alternate: '#fffaf0',
      },
    },
  {
      id: 'dots-violet-field',
      label: 'Dots / Violet Field',
      frame: 'landscape',
      viewId: 'dots',
      theme: THEMES.DARK,
      viewState: {
        ...DOTS_DEFAULT_SETTINGS,
        shape: 'square',
        gapX: 0.3,
        gapY: 0.3,
        inactiveOpacity: 7,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#8b5cf6',
        alternate: '#1f1636',
      },
    },
  {
      id: 'pie-ivory-outline',
      label: 'Pie / Ivory Outline',
      frame: 'square',
      viewId: 'pie',
      theme: THEMES.LIGHT,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'circle',
        style: 'outline',
        fullScreen: true,
        decimals: 2,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#111827',
        alternate: '#fffaf0',
      },
    },
  {
      id: 'pie-noir-outline',
      label: 'Pie / Noir Outline',
      frame: 'landscape',
      viewId: 'pie',
      theme: THEMES.DARK,
      viewState: {
        ...PIE_DEFAULT_SETTINGS,
        shape: 'rectangle',
        style: 'outline',
        fullScreen: true,
        decimals: 1,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#f8fafc',
        alternate: '#020617',
      },
    },
  {
      id: 'progress-gold-line',
      label: 'Progress / Gold Line',
      frame: 'landscape',
      viewId: 'progress',
      theme: THEMES.DARK,
      viewState: {
        ...PROGRESS_DEFAULT_SETTINGS,
        mode: 'line',
        fullScreen: true,
        decimals: 4,
        fontSize: 0.92,
        lineWidth: 20,
        spaceTop: 8,
        spaceRight: 4,
        spaceBottom: 8,
        spaceLeft: 4,
        primary: '#fbbf24',
        alternate: '#111827',
      },
    },
  {
      id: 'all-chartreuse-grid',
      label: 'All / Chartreuse Grid',
      frame: 'square',
      viewId: 'all',
      theme: THEMES.DARK,
      viewState: {
        ...ALL_DEFAULT_SETTINGS,
        dotsMode: 'custom',
        dotsCount: 196,
        showDays: true,
        showPercentBox: true,
        showPerimeter: true,
        shape: 'square',
        percentBoxSize: 'small',
        perimeterThickness: 5,
        gapX: 0.35,
        gapY: 0.35,
        spaceTop: 0,
        spaceRight: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        primary: '#bef264',
        alternate: '#111111',
      },
    },
];


const GENERATED_SAMPLE_ITEMS = [
  {
    id: 'countdown-cream-all',
    label: 'Countdown / Cream Grid',
    frame: 'portrait',
    viewId: 'countdown',
    theme: THEMES.LIGHT,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'all',
      labels: true,
      frame: false,
      fontSize: 0.58,
      spaceTop: 4,
      spaceRight: 4,
      spaceBottom: 4,
      spaceLeft: 4,
      primary: '#0f172a',
      alternate: '#fff7ed',
    },
  },
  {
    id: 'countdown-sand-seconds',
    label: 'Countdown / Sand Seconds',
    frame: 'square',
    viewId: 'countdown',
    theme: THEMES.LIGHT,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'seconds',
      labels: false,
      frame: false,
      fontSize: 0.28,
      spaceTop: 10,
      spaceRight: 6,
      spaceBottom: 6,
      spaceLeft: 6,
      primary: '#111827',
      alternate: '#f5f5dc',
    },
  },
  {
    id: 'countdown-cyan-hours',
    label: 'Countdown / Cyan Hours',
    frame: 'landscape',
    viewId: 'countdown',
    theme: THEMES.DARK,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'hours',
      labels: true,
      frame: false,
      fontSize: 0.62,
      spaceTop: 3,
      spaceRight: 3,
      spaceBottom: 3,
      spaceLeft: 3,
      primary: '#22d3ee',
      alternate: '#082f49',
    },
  },
  {
    id: 'countdown-coral-days',
    label: 'Countdown / Coral Days',
    frame: 'square',
    viewId: 'countdown',
    theme: THEMES.LIGHT,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'days',
      labels: true,
      frame: false,
      fontSize: 0.6,
      spaceTop: 8,
      spaceRight: 5,
      spaceBottom: 5,
      spaceLeft: 5,
      primary: '#ea580c',
      alternate: '#fff7ed',
    },
  },
  {
    id: 'countdown-violet-minutes',
    label: 'Countdown / Violet Minutes',
    frame: 'portrait',
    viewId: 'countdown',
    theme: THEMES.DARK,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'minutes',
      labels: false,
      frame: false,
      fontSize: 0.68,
      spaceTop: 5,
      spaceRight: 5,
      spaceBottom: 5,
      spaceLeft: 5,
      primary: '#a78bfa',
      alternate: '#1e1b4b',
    },
  },
  {
    id: 'countdown-navy-clean',
    label: 'Countdown / Navy Clean',
    frame: 'landscape',
    viewId: 'countdown',
    theme: THEMES.LIGHT,
    viewState: {
      ...COUNTDOWN_DEFAULT_SETTINGS,
      mode: 'all',
      labels: true,
      frame: false,
      fontSize: 0.52,
      spaceTop: 2,
      spaceRight: 2,
      spaceBottom: 2,
      spaceLeft: 2,
      primary: '#0f172a',
      alternate: '#ecfeff',
    },
  },
  {
    id: 'dots-cobalt-circles',
    label: 'Dots / Cobalt Circles',
    frame: 'square',
    viewId: 'dots',
    theme: THEMES.LIGHT,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'circle',
      gapX: 0.32,
      gapY: 0.32,
      inactiveOpacity: 4,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#1d4ed8',
      alternate: '#fffaf0',
    },
  },
  {
    id: 'dots-mint-squares',
    label: 'Dots / Mint Squares',
    frame: 'landscape',
    viewId: 'dots',
    theme: THEMES.DARK,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'square',
      gapX: 0.28,
      gapY: 0.28,
      inactiveOpacity: 6,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#34d399',
      alternate: '#052e16',
    },
  },
  {
    id: 'dots-amber-circles',
    label: 'Dots / Amber Circles',
    frame: 'portrait',
    viewId: 'dots',
    theme: THEMES.LIGHT,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'circle',
      gapX: 0.42,
      gapY: 0.42,
      inactiveOpacity: 7,
      spaceTop: 1,
      spaceRight: 1,
      spaceBottom: 1,
      spaceLeft: 1,
      primary: '#f59e0b',
      alternate: '#fffbeb',
    },
  },
  {
    id: 'dots-cyan-triangles',
    label: 'Dots / Cyan Triangles',
    frame: 'square',
    viewId: 'dots',
    theme: THEMES.DARK,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'triangle',
      triangleMode: 'alternating',
      gapX: 0.45,
      gapY: 0.45,
      inactiveOpacity: 8,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#67e8f9',
      alternate: '#083344',
    },
  },
  {
    id: 'dots-rose-grid',
    label: 'Dots / Rose Grid',
    frame: 'landscape',
    viewId: 'dots',
    theme: THEMES.DARK,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'square',
      gapX: 0.38,
      gapY: 0.38,
      inactiveOpacity: 5,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#fb7185',
      alternate: '#1f2937',
    },
  },
  {
    id: 'dots-noir-dense',
    label: 'Dots / Noir Dense',
    frame: 'portrait',
    viewId: 'dots',
    theme: THEMES.LIGHT,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'circle',
      gapX: 0.22,
      gapY: 0.22,
      inactiveOpacity: 3,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#111827',
      alternate: '#f8fafc',
    },
  },
  {
    id: 'dots-lilac-field',
    label: 'Dots / Lilac Field',
    frame: 'square',
    viewId: 'dots',
    theme: THEMES.LIGHT,
    viewState: {
      ...DOTS_DEFAULT_SETTINGS,
      shape: 'circle',
      gapX: 0.34,
      gapY: 0.34,
      inactiveOpacity: 6,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#8b5cf6',
      alternate: '#faf5ff',
    },
  },
  {
    id: 'pie-cyan-circle',
    label: 'Pie / Cyan Circle',
    frame: 'square',
    viewId: 'pie',
    theme: THEMES.DARK,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'circle',
      style: 'filled',
      fullScreen: true,
      decimals: 2,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#22d3ee',
      alternate: '#0f172a',
    },
  },
  {
    id: 'pie-violet-rectangle',
    label: 'Pie / Violet Rectangle',
    frame: 'landscape',
    viewId: 'pie',
    theme: THEMES.DARK,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'rectangle',
      style: 'filled',
      fullScreen: true,
      decimals: 2,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#8b5cf6',
      alternate: '#111827',
    },
  },
  {
    id: 'pie-amber-outline',
    label: 'Pie / Amber Outline',
    frame: 'square',
    viewId: 'pie',
    theme: THEMES.LIGHT,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'circle',
      style: 'outline',
      fullScreen: true,
      decimals: 2,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#f59e0b',
      alternate: '#fffbeb',
    },
  },
  {
    id: 'pie-forest-outline',
    label: 'Pie / Forest Outline',
    frame: 'landscape',
    viewId: 'pie',
    theme: THEMES.DARK,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'rectangle',
      style: 'outline',
      fullScreen: true,
      decimals: 1,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#34d399',
      alternate: '#052e16',
    },
  },
  {
    id: 'pie-cream-circle',
    label: 'Pie / Cream Circle',
    frame: 'portrait',
    viewId: 'pie',
    theme: THEMES.LIGHT,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'circle',
      style: 'filled',
      fullScreen: false,
      decimals: 3,
      spaceTop: 6,
      spaceRight: 6,
      spaceBottom: 6,
      spaceLeft: 6,
      primary: '#0f172a',
      alternate: '#fff7ed',
    },
  },
  {
    id: 'pie-coral-outline',
    label: 'Pie / Coral Outline',
    frame: 'square',
    viewId: 'pie',
    theme: THEMES.LIGHT,
    viewState: {
      ...PIE_DEFAULT_SETTINGS,
      shape: 'rectangle',
      style: 'outline',
      fullScreen: true,
      decimals: 0,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#ea580c',
      alternate: '#fff7ed',
    },
  },
  {
    id: 'progress-ivory-line',
    label: 'Progress / Ivory Line',
    frame: 'landscape',
    viewId: 'progress',
    theme: THEMES.LIGHT,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'line',
      fullScreen: true,
      decimals: 5,
      fontSize: 0.78,
      lineWidth: 14,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#111827',
      alternate: '#fffaf0',
    },
  },
  {
    id: 'progress-emerald-field',
    label: 'Progress / Emerald Field',
    frame: 'square',
    viewId: 'progress',
    theme: THEMES.DARK,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'field',
      fullScreen: true,
      decimals: 2,
      fontSize: 0.88,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#34d399',
      alternate: '#052e16',
    },
  },
  {
    id: 'progress-cobalt-line',
    label: 'Progress / Cobalt Line',
    frame: 'portrait',
    viewId: 'progress',
    theme: THEMES.LIGHT,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'line',
      fullScreen: true,
      decimals: 6,
      fontSize: 0.72,
      lineWidth: 16,
      spaceTop: 4,
      spaceRight: 4,
      spaceBottom: 4,
      spaceLeft: 4,
      primary: '#2563eb',
      alternate: '#eff6ff',
    },
  },
  {
    id: 'progress-coral-field',
    label: 'Progress / Coral Field',
    frame: 'landscape',
    viewId: 'progress',
    theme: THEMES.LIGHT,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'field',
      fullScreen: true,
      decimals: 1,
      fontSize: 0.92,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#fb7185',
      alternate: '#fff1f2',
    },
  },
  {
    id: 'progress-violet-line',
    label: 'Progress / Violet Line',
    frame: 'square',
    viewId: 'progress',
    theme: THEMES.DARK,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'line',
      fullScreen: true,
      decimals: 4,
      fontSize: 0.74,
      lineWidth: 18,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#a78bfa',
      alternate: '#1e1b4b',
    },
  },
  {
    id: 'progress-noir-field',
    label: 'Progress / Noir Field',
    frame: 'square',
    viewId: 'progress',
    theme: THEMES.LIGHT,
    viewState: {
      ...PROGRESS_DEFAULT_SETTINGS,
      mode: 'field',
      fullScreen: true,
      decimals: 0,
      fontSize: 0.86,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#020617',
      alternate: '#f8fafc',
    },
  },
  {
    id: 'all-cobalt-mosaic',
    label: 'All / Cobalt Mosaic',
    frame: 'square',
    viewId: 'all',
    theme: THEMES.LIGHT,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'custom',
      dotsCount: 64,
      showDays: true,
      showPercentBox: true,
      showPerimeter: true,
      shape: 'square',
      percentBoxSize: 'small',
      perimeterThickness: 5,
      gapX: 0.34,
      gapY: 0.34,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#2563eb',
      alternate: '#eff6ff',
    },
  },
  {
    id: 'all-coral-stack',
    label: 'All / Coral Stack',
    frame: 'portrait',
    viewId: 'all',
    theme: THEMES.LIGHT,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'custom',
      dotsCount: 48,
      showDays: true,
      showPercentBox: true,
      showPerimeter: false,
      shape: 'circle',
      summaryLayout: 'row',
      gapX: 0.38,
      gapY: 0.38,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#fb7185',
      alternate: '#fff1f2',
    },
  },
  {
    id: 'all-noir-12',
    label: 'All / Noir Twelve',
    frame: 'square',
    viewId: 'all',
    theme: THEMES.DARK,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'custom',
      dotsCount: 12,
      showDays: true,
      showPercentBox: true,
      showPerimeter: true,
      shape: 'circle',
      percentBoxSize: 'small',
      perimeterThickness: 5,
      gapX: 0.5,
      gapY: 0.5,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#ffffff',
      alternate: '#000000',
    },
  },
  {
    id: 'all-mint-grid',
    label: 'All / Mint Grid',
    frame: 'landscape',
    viewId: 'all',
    theme: THEMES.DARK,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'custom',
      dotsCount: 96,
      showDays: false,
      showPercentBox: true,
      showPerimeter: true,
      shape: 'square',
      percentBoxSize: 'small',
      perimeterThickness: 4,
      gapX: 0.3,
      gapY: 0.3,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#34d399',
      alternate: '#052e16',
    },
  },
  {
    id: 'all-ivory-minimal',
    label: 'All / Ivory Minimal',
    frame: 'square',
    viewId: 'all',
    theme: THEMES.LIGHT,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'days',
      showDays: true,
      showPercentBox: false,
      showPerimeter: true,
      shape: 'circle',
      perimeterThickness: 4,
      gapX: 0.42,
      gapY: 0.42,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#111827',
      alternate: '#fffaf0',
    },
  },
  {
    id: 'all-violet-dense',
    label: 'All / Violet Dense',
    frame: 'landscape',
    viewId: 'all',
    theme: THEMES.DARK,
    viewState: {
      ...ALL_DEFAULT_SETTINGS,
      dotsMode: 'custom',
      dotsCount: 144,
      showDays: true,
      showPercentBox: true,
      showPerimeter: true,
      shape: 'triangle',
      triangleMode: 'alternating',
      percentBoxSize: 'small',
      perimeterThickness: 5,
      gapX: 0.34,
      gapY: 0.34,
      spaceTop: 0,
      spaceRight: 0,
      spaceBottom: 0,
      spaceLeft: 0,
      primary: '#a78bfa',
      alternate: '#1e1b4b',
    },
  },
];

const SAMPLE_SOURCE_ITEMS = [...RAW_SAMPLE_ITEMS, ...GENERATED_SAMPLE_ITEMS];

export const SAMPLE_CATEGORY_ORDER = ['countdown', 'dots', 'pie', 'progress', 'all'];

export const SAMPLE_ITEMS = SAMPLE_SOURCE_ITEMS.map((item) => ({
  category: item.viewId,
  tags: item.tags ?? [],
  ...item,
}));

export const getSampleById = (sampleId) => {
  return SAMPLE_ITEMS.find((item) => item.id === sampleId) ?? null;
};

export const getSamplesByCategory = (category) => {
  return SAMPLE_ITEMS.filter((item) => item.category === category);
};
